canary:
  namespaces: ["canary"]
  excludes: [
    "workflow.signal",
    "workflow.visibility",
    "workflow.searchAttributes",
    "workflow.concurrent-execution",
    "workflow.query",
    "workflow.timeout",
    "workflow.localactivity",
    "workflow.cancellation",
    "workflow.retry",
    "workflow.reset",
    "workflow.archival.history",
    "workflow.archival.visibility"
  ]

temporal:
  service: "frontend"
  host: "127.0.0.1:7233"
